trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build'

# TODO: Re-enable tests when traindata is available in DevOps
#- task: DotNetCoreCLI@2
#  displayName: 'Run test suite'
#  inputs:
#    command: 'test'

- task: SSH@0
  inputs:
    sshEndpoint: 'Azure VM datacore'
    runOptions: 'commands'
    commands: './publish.sh'